apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ia-marketplace-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: ia-marketplace.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: ia-marketplace-app
                port:
                  number: 80
